package com.flipiq.property.dto;

import java.math.BigDecimal;
import java.util.List;

public record FlipOpportunityPropertyDto(
		String id,
		String address,
		String city,
		String state,
		String zipCode,
		String propertyType,
		BigDecimal listPrice,
		BigDecimal estimatedValue,
		BigDecimal estimatedRehabCost,
		BigDecimal closingCosts,
		BigDecimal holdingCosts,
		BigDecimal estimatedProfit,
		BigDecimal roiPercent,
		BigDecimal discountPercent,
		BigDecimal priceDropAmount,
		Integer daysOnMarket,
		String rehabRisk,
		Integer bedrooms,
		BigDecimal bathrooms,
		Integer livingArea,
		Integer lotSize,
		Integer yearBuilt,
		BigDecimal hoaFee,
		String status,
		String listingType,
		String listedDate,
		String lastSeenDate,
		String mlsName,
		String mlsNumber,
		String listingAgentName,
		String listingAgentPhone,
		String listingAgentEmail,
		String listingOfficeName,
		String listingOfficePhone,
		Integer historyEventCount,
		Double latitude,
		Double longitude,
		Integer flipScore,
		String recommendation,
		List<String> highlights) {
}
